### PR TITLE
Fix type dependency for unplugin-vue-components

### LINKED ISSUE #3: Optional dependency gives build error
image

Using vite 2.9.5, vue-tsc 0.34.10 and typescript 4.6.3

### PR DESCRIPTION
**Pull request by tomhooijenga**
This should fix #3

### CODE REVIEW

File: packages/headlessui-float-vue/src/resolver.ts [hunk 1]
```diff
@@ -1,3 +1,4 @@
+// @ts-ignore
```
Comment (ycs77) [inline packages/headlessui-float-vue/src/resolver.ts:1]: Hi! can you change to `/** @ts-ignore */`?

Comment (tomhooijenga) [reply packages/headlessui-float-vue/src/resolver.ts]: Sure, done!

**Comment by ycs77** [comment]
Now released on v0.5.2
